package cosco.vsagent.mapping.base;



import java.util.Date;


/**
 * Basport generated by MyEclipse - Hibernate Tools
 */

public class Basport  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String porttype;
     private String portcode;
     private String cname;
     private String ename;
     private String nationcode;
     private String ifbaseprot;
     private String makercode;
     private String maker;
     private Date madetime;
     private String modicode;
     private String modifier;
     private Date moditime;
     private String Sequence;


    // Constructors

    public String getSequence() {
		return Sequence;
	}

	public void setSequence(String sequence) {
		Sequence = sequence;
	}

	/** default constructor */
    public Basport() {
    }

	/** minimal constructor */
    public Basport(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Basport(Integer mainkey, String portcode, String cname, String ename, String nationcode, String ifbaseprot, String makercode, String maker, Date madetime, String modicode, String modifier, Date moditime, String porttype) {
        this.mainkey = mainkey;
        this.portcode = portcode;
        this.cname = cname;
        this.ename = ename;
        this.nationcode = nationcode;
        this.ifbaseprot = ifbaseprot;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
        this.porttype = porttype;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getPortcode() {
        return this.portcode;
    }
    
    public void setPortcode(String portcode) {
        this.portcode = portcode;
    }

    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }

    public String getNationcode() {
        return this.nationcode;
    }
    
    public void setNationcode(String nationcode) {
        this.nationcode = nationcode;
    }

    public String getIfbaseprot() {
        return this.ifbaseprot;
    }
    
    public void setIfbaseprot(String ifbaseprot) {
        this.ifbaseprot = ifbaseprot;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Date getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Date madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Date getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Date moditime) {
        this.moditime = moditime;
    }

    public String getPorttype() {
        return this.porttype;
    }
    
    public void setPorttype(String porttype) {
        this.porttype = porttype;
    }
   








}