package cosco.vsagent.mapping.base;

import java.sql.Time;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Basvslvoy generated by MyEclipse - Hibernate Tools
 */

public class Basvslvoy  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private Integer vslkey;
     private String vslcode;
     private String vslcname;
     private String vslename;
     private String voyage;
     private String ie;
     private String cuscode;
     private String linename;
     private String locksign;
     private String secvslsign;
     private String tradetype;
     private String makercode;
     private String maker;
     private Timestamp madetime;
     private String modicode;
     private String modifier;
     private Timestamp moditime;
     private String linecode;
     private String custcode;
     private String custcname;
     private String linetype;
     private Date saildate;
     private Date arrdate;
     private Time arrtime;
     private Time sailtime;
     private String ownagent;
     private String cntronly;
     private String needclose;
     private String transid;
     private Integer vslldkey;
     private String sequence;
     private Set<Basvslvoy> courses = new HashSet<Basvslvoy>();
     
     private Integer leaveday;  //¿Î∏€ÃÏ ˝

    // Constructors

    ///////
    public Integer getLeaveday() {
		return leaveday;
	}

	public void setLeaveday(Integer leaveday) {
		this.leaveday = leaveday;
	}
	
	
	/////////////////////////////////

	/** default constructor */
    public Basvslvoy() {
    }

	/** minimal constructor */
    public Basvslvoy(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Basvslvoy(Integer mainkey, Integer vslkey, String vslcode, String vslcname, String vslename, String voyage, String ie, String cuscode, String linename, String locksign, String secvslsign, String tradetype, String makercode, String maker, Timestamp madetime, String modicode, String modifier, Timestamp moditime, String linecode, String custcode, String custcname, String linetype, Date saildate, Date arrdate, Time arrtime, Time sailtime, String ownagent, String cntronly, String needclose, String transid, Integer vslldkey) {
        this.mainkey = mainkey;
        this.vslkey = vslkey;
        this.vslcode = vslcode;
        this.vslcname = vslcname;
        this.vslename = vslename;
        this.voyage = voyage;
        this.ie = ie;
        this.cuscode = cuscode;
        this.linename = linename;
        this.locksign = locksign;
        this.secvslsign = secvslsign;
        this.tradetype = tradetype;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
        this.linecode = linecode;
        this.custcode = custcode;
        this.custcname = custcname;
        this.linetype = linetype;
        this.saildate = saildate;
        this.arrdate = arrdate;
        this.arrtime = arrtime;
        this.sailtime = sailtime;
        this.ownagent = ownagent;
        this.cntronly = cntronly;
        this.needclose = needclose;
        this.transid = transid;
        this.vslldkey = vslldkey;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public Integer getVslkey() {
        return this.vslkey;
    }
    
    public void setVslkey(Integer vslkey) {
        this.vslkey = vslkey;
    }

    public String getVslcode() {
        return this.vslcode;
    }
    
    public void setVslcode(String vslcode) {
        this.vslcode = vslcode;
    }

    public String getVslcname() {
        return this.vslcname;
    }
    
    public void setVslcname(String vslcname) {
        this.vslcname = vslcname;
    }

    public String getVslename() {
        return this.vslename;
    }
    
    public void setVslename(String vslename) {
        this.vslename = vslename;
    }

    public String getVoyage() {
        return this.voyage;
    }
    
    public void setVoyage(String voyage) {
        this.voyage = voyage;
    }

    public String getIe() {
        return this.ie;
    }
    
    public void setIe(String ie) {
        this.ie = ie;
    }

    public String getCuscode() {
        return this.cuscode;
    }
    
    public void setCuscode(String cuscode) {
        this.cuscode = cuscode;
    }

    public String getLinename() {
        return this.linename;
    }
    
    public void setLinename(String linename) {
        this.linename = linename;
    }

    public String getLocksign() {
        return this.locksign;
    }
    
    public void setLocksign(String locksign) {
        this.locksign = locksign;
    }

    public String getSecvslsign() {
        return this.secvslsign;
    }
    
    public void setSecvslsign(String secvslsign) {
        this.secvslsign = secvslsign;
    }

    public String getTradetype() {
        return this.tradetype;
    }
    
    public void setTradetype(String tradetype) {
        this.tradetype = tradetype;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Timestamp getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Timestamp madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Timestamp moditime) {
        this.moditime = moditime;
    }

    public String getLinecode() {
        return this.linecode;
    }
    
    public void setLinecode(String linecode) {
        this.linecode = linecode;
    }

    public String getCustcode() {
        return this.custcode;
    }
    
    public void setCustcode(String custcode) {
        this.custcode = custcode;
    }

    public String getCustcname() {
        return this.custcname;
    }
    
    public void setCustcname(String custcname) {
        this.custcname = custcname;
    }

    public String getLinetype() {
        return this.linetype;
    }
    
    public void setLinetype(String linetype) {
        this.linetype = linetype;
    }
  
    public Date getSaildate() {
        return this.saildate;
    }
    
    public void setSaildate(Date saildate) {
        this.saildate = saildate;
    }

    public Date getArrdate() {
        return this.arrdate;
    }
    
    public void setArrdate(Date arrdate) {
        this.arrdate = arrdate;
    }

   
    

    public String getOwnagent() {
        return this.ownagent;
    }
    
    public void setOwnagent(String ownagent) {
        this.ownagent = ownagent;
    }

    public String getCntronly() {
        return this.cntronly;
    }
    
    public void setCntronly(String cntronly) {
        this.cntronly = cntronly;
    }

    public String getNeedclose() {
        return this.needclose;
    }
    
    public void setNeedclose(String needclose) {
        this.needclose = needclose;
    }

    public String getTransid() {
        return this.transid;
    }
    
    public void setTransid(String transid) {
        this.transid = transid;
    }

    public Integer getVslldkey() {
        return this.vslldkey;
    }
    
    public void setVslldkey(Integer vslldkey) {
        this.vslldkey = vslldkey;
    }

	public Time getArrtime() {
		return arrtime;
	}

	public void setArrtime(Time arrtime) {
		this.arrtime = arrtime;
	}

	public Time getSailtime() {
		return sailtime;
	}

	public void setSailtime(Time sailtime) {
		this.sailtime = sailtime;
	}

	public Set<Basvslvoy> getCourses() {
		return courses;
	}

	public void setCourses(Set<Basvslvoy> courses) {
		this.courses = courses;
	}

	public String getSequence() {
		return sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}
   



}