package cosco.vsagent.mapping.base;



/**
 * Basvvcarr generated by MyEclipse - Hibernate Tools
 */

public class Basvvcarr  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private Integer vslvoykey;
     private String carrcode;
     private String carrename;
     private String dffsign;
     private String vslmanager;
     private String frenanager;
     private String rcve;
     private String rcvf;
     private String gtve;
     private String gtvf;
     private String remark;
     private String smve;
     private String smvf;
     private String remkvf;
     private String sequence_fk;

    // Constructors

    /** default constructor */
    public Basvvcarr() {
    }

	/** minimal constructor */
    public Basvvcarr(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Basvvcarr(Integer mainkey, Integer vslvoykey, String carrcode, String carrename, String dffsign, String vslmanager, String frenanager, String rcve, String rcvf, String gtve, String gtvf, String remark, String smve, String smvf, String remkvf, String sequence_fk) {
        this.mainkey = mainkey;
        this.vslvoykey = vslvoykey;
        this.carrcode = carrcode;
        this.carrename = carrename;
        this.dffsign = dffsign;
        this.vslmanager = vslmanager;
        this.frenanager = frenanager;
        this.rcve = rcve;
        this.rcvf = rcvf;
        this.gtve = gtve;
        this.gtvf = gtvf;
        this.remark = remark;
        this.smve = smve;
        this.smvf = smvf;
        this.remkvf = remkvf;
        this.sequence_fk = sequence_fk;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public Integer getVslvoykey() {
        return this.vslvoykey;
    }
    
    public void setVslvoykey(Integer vslvoykey) {
        this.vslvoykey = vslvoykey;
    }

    public String getCarrcode() {
        return this.carrcode;
    }
    
    public void setCarrcode(String carrcode) {
        this.carrcode = carrcode;
    }

    public String getCarrename() {
        return this.carrename;
    }
    
    public void setCarrename(String carrename) {
        this.carrename = carrename;
    }

    public String getDffsign() {
        return this.dffsign;
    }
    
    public void setDffsign(String dffsign) {
        this.dffsign = dffsign;
    }

    public String getVslmanager() {
        return this.vslmanager;
    }
    
    public void setVslmanager(String vslmanager) {
        this.vslmanager = vslmanager;
    }

    public String getFrenanager() {
        return this.frenanager;
    }
    
    public void setFrenanager(String frenanager) {
        this.frenanager = frenanager;
    }

    public String getRcve() {
        return this.rcve;
    }
    
    public void setRcve(String rcve) {
        this.rcve = rcve;
    }

    public String getRcvf() {
        return this.rcvf;
    }
    
    public void setRcvf(String rcvf) {
        this.rcvf = rcvf;
    }

    public String getGtve() {
        return this.gtve;
    }
    
    public void setGtve(String gtve) {
        this.gtve = gtve;
    }

    public String getGtvf() {
        return this.gtvf;
    }
    
    public void setGtvf(String gtvf) {
        this.gtvf = gtvf;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSmve() {
        return this.smve;
    }
    
    public void setSmve(String smve) {
        this.smve = smve;
    }

    public String getSmvf() {
        return this.smvf;
    }
    
    public void setSmvf(String smvf) {
        this.smvf = smvf;
    }

    public String getRemkvf() {
        return this.remkvf;
    }
    
    public void setRemkvf(String remkvf) {
        this.remkvf = remkvf;
    }

	public String getSequence_fk() {
		return this.sequence_fk;
	}

	public void setSequence_fk(String sequence_fk) {
		this.sequence_fk = sequence_fk;
	}
   
}