package cosco.vsagent.mapping.ecd;


import cosco.vsagent.mapping.Party;



/**
 * Ecdbkparty generated by MyEclipse - Hibernate Tools
 */

public class Ecdbkparty  implements java.io.Serializable, Party {


    // Fields    

     private Integer mainkey;
     private Integer bkkey;
     private Integer vslvoykey;
     private String partytype;
     private String partyname;
     private String partymsg;
     private String autoprime;
     private String vslkey_seq;
     private String blno_seq;


    // Constructors

    /** default constructor */
    public Ecdbkparty() {
    }

	/** minimal constructor */
    public Ecdbkparty(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Ecdbkparty(Integer mainkey, Integer bkkey, Integer vslvoykey, String partytype, String partyname, String partymsg, String autoprime) {
        this.mainkey = mainkey;
        this.bkkey = bkkey;
        this.vslvoykey = vslvoykey;
        this.partytype = partytype;
        this.partyname = partyname;
        this.partymsg = partymsg;
        this.autoprime = autoprime;
    }

   
    // Property accessors

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#getMainkey()
	 */
    public Integer getMainkey() {
        return this.mainkey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#setMainkey(java.lang.Integer)
	 */
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#getBkkey()
	 */
    public Integer getBkkey() {
        return this.bkkey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#setBkkey(java.lang.Integer)
	 */
    public void setBkkey(Integer bkkey) {
        this.bkkey = bkkey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#getVslvoykey()
	 */
    public Integer getVslvoykey() {
        return this.vslvoykey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#setVslvoykey(java.lang.Integer)
	 */
    public void setVslvoykey(Integer vslvoykey) {
        this.vslvoykey = vslvoykey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#getPartytype()
	 */
    public String getPartytype() {
        return this.partytype;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#setPartytype(java.lang.String)
	 */
    public void setPartytype(String partytype) {
        this.partytype = partytype;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#getPartyname()
	 */
    public String getPartyname() {
        return this.partyname;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#setPartyname(java.lang.String)
	 */
    public void setPartyname(String partyname) {
        this.partyname = partyname;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#getPartymsg()
	 */
    public String getPartymsg() {
        return this.partymsg;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#setPartymsg(java.lang.String)
	 */
    public void setPartymsg(String partymsg) {
        this.partymsg = partymsg;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#getAutoprime()
	 */
    public String getAutoprime() {
        return this.autoprime;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkparty#setAutoprime(java.lang.String)
	 */
    public void setAutoprime(String autoprime) {
        this.autoprime = autoprime;
    }

	public String getVslkey_seq() {
		return vslkey_seq;
	}

	public void setVslkey_seq(String vslkey_seq) {
		this.vslkey_seq = vslkey_seq;
	}

	public String getBlno_seq() {
		return blno_seq;
	}

	public void setBlno_seq(String blno_seq) {
		this.blno_seq = blno_seq;
	}
   








}