package cosco.xml.mapping;



/**
 * Xmlbkparty generated by MyEclipse - Hibernate Tools
 */

public class Xmlbkparty  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String bcflag;
     private String ieflag;
     private Integer xmlbkkey;
     private Integer vslvoykey;
     private String partytype;
     private String partyname;
     private String partyid;
     private String partymsg;
     private String ptline;
     private String ptcity;
     private String ptentid;
     private String ptentname;
     private String ptpostid;
     private String ptcountry;
     private String ptctcm1;
     private String ptctty1;
     private String ptctcm2;
     private String ptctty2;
     private String ptctcm3;
     private String ptctty3;
     private String contname;
     private String ctctcm1;
     private String ctctty1;
     private String ctctcm2;
     private String ctctty2;
     private String ctctcm3;
     private String ctctty3;


    // Constructors

    /** default constructor */
    public Xmlbkparty() {
    }

	/** minimal constructor */
    public Xmlbkparty(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Xmlbkparty(Integer mainkey, String bcflag, String ieflag, Integer xmlbkkey, Integer vslvoykey, String partytype, String partyname, String partyid, String partymsg, String ptline, String ptcity, String ptentid, String ptentname, String ptpostid, String ptcountry, String ptctcm1, String ptctty1, String ptctcm2, String ptctty2, String ptctcm3, String ptctty3, String contname, String ctctcm1, String ctctty1, String ctctcm2, String ctctty2, String ctctcm3, String ctctty3) {
        this.mainkey = mainkey;
        this.bcflag = bcflag;
        this.ieflag = ieflag;
        this.xmlbkkey = xmlbkkey;
        this.vslvoykey = vslvoykey;
        this.partytype = partytype;
        this.partyname = partyname;
        this.partyid = partyid;
        this.partymsg = partymsg;
        this.ptline = ptline;
        this.ptcity = ptcity;
        this.ptentid = ptentid;
        this.ptentname = ptentname;
        this.ptpostid = ptpostid;
        this.ptcountry = ptcountry;
        this.ptctcm1 = ptctcm1;
        this.ptctty1 = ptctty1;
        this.ptctcm2 = ptctcm2;
        this.ptctty2 = ptctty2;
        this.ptctcm3 = ptctcm3;
        this.ptctty3 = ptctty3;
        this.contname = contname;
        this.ctctcm1 = ctctcm1;
        this.ctctty1 = ctctty1;
        this.ctctcm2 = ctctcm2;
        this.ctctty2 = ctctty2;
        this.ctctcm3 = ctctcm3;
        this.ctctty3 = ctctty3;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getBcflag() {
        return this.bcflag;
    }
    
    public void setBcflag(String bcflag) {
        this.bcflag = bcflag;
    }

    public String getIeflag() {
        return this.ieflag;
    }
    
    public void setIeflag(String ieflag) {
        this.ieflag = ieflag;
    }

    public Integer getXmlbkkey() {
        return this.xmlbkkey;
    }
    
    public void setXmlbkkey(Integer xmlbkkey) {
        this.xmlbkkey = xmlbkkey;
    }

    public Integer getVslvoykey() {
        return this.vslvoykey;
    }
    
    public void setVslvoykey(Integer vslvoykey) {
        this.vslvoykey = vslvoykey;
    }

    public String getPartytype() {
        return this.partytype;
    }
    
    public void setPartytype(String partytype) {
        this.partytype = partytype;
    }

    public String getPartyname() {
        return this.partyname;
    }
    
    public void setPartyname(String partyname) {
        this.partyname = partyname;
    }

    public String getPartyid() {
        return this.partyid;
    }
    
    public void setPartyid(String partyid) {
        this.partyid = partyid;
    }

    public String getPartymsg() {
        return this.partymsg;
    }
    
    public void setPartymsg(String partymsg) {
        this.partymsg = partymsg;
    }

    public String getPtline() {
        return this.ptline;
    }
    
    public void setPtline(String ptline) {
        this.ptline = ptline;
    }

    public String getPtcity() {
        return this.ptcity;
    }
    
    public void setPtcity(String ptcity) {
        this.ptcity = ptcity;
    }

    public String getPtentid() {
        return this.ptentid;
    }
    
    public void setPtentid(String ptentid) {
        this.ptentid = ptentid;
    }

    public String getPtentname() {
        return this.ptentname;
    }
    
    public void setPtentname(String ptentname) {
        this.ptentname = ptentname;
    }

    public String getPtpostid() {
        return this.ptpostid;
    }
    
    public void setPtpostid(String ptpostid) {
        this.ptpostid = ptpostid;
    }

    public String getPtcountry() {
        return this.ptcountry;
    }
    
    public void setPtcountry(String ptcountry) {
        this.ptcountry = ptcountry;
    }

    public String getPtctcm1() {
        return this.ptctcm1;
    }
    
    public void setPtctcm1(String ptctcm1) {
        this.ptctcm1 = ptctcm1;
    }

    public String getPtctty1() {
        return this.ptctty1;
    }
    
    public void setPtctty1(String ptctty1) {
        this.ptctty1 = ptctty1;
    }

    public String getPtctcm2() {
        return this.ptctcm2;
    }
    
    public void setPtctcm2(String ptctcm2) {
        this.ptctcm2 = ptctcm2;
    }

    public String getPtctty2() {
        return this.ptctty2;
    }
    
    public void setPtctty2(String ptctty2) {
        this.ptctty2 = ptctty2;
    }

    public String getPtctcm3() {
        return this.ptctcm3;
    }
    
    public void setPtctcm3(String ptctcm3) {
        this.ptctcm3 = ptctcm3;
    }

    public String getPtctty3() {
        return this.ptctty3;
    }
    
    public void setPtctty3(String ptctty3) {
        this.ptctty3 = ptctty3;
    }

    public String getContname() {
        return this.contname;
    }
    
    public void setContname(String contname) {
        this.contname = contname;
    }

    public String getCtctcm1() {
        return this.ctctcm1;
    }
    
    public void setCtctcm1(String ctctcm1) {
        this.ctctcm1 = ctctcm1;
    }

    public String getCtctty1() {
        return this.ctctty1;
    }
    
    public void setCtctty1(String ctctty1) {
        this.ctctty1 = ctctty1;
    }

    public String getCtctcm2() {
        return this.ctctcm2;
    }
    
    public void setCtctcm2(String ctctcm2) {
        this.ctctcm2 = ctctcm2;
    }

    public String getCtctty2() {
        return this.ctctty2;
    }
    
    public void setCtctty2(String ctctty2) {
        this.ctctty2 = ctctty2;
    }

    public String getCtctcm3() {
        return this.ctctcm3;
    }
    
    public void setCtctcm3(String ctctcm3) {
        this.ctctcm3 = ctctcm3;
    }

    public String getCtctty3() {
        return this.ctctty3;
    }
    
    public void setCtctty3(String ctctty3) {
        this.ctctty3 = ctctty3;
    }
   








}