package cosco.xml.mapping;



/**
 * Xmlbkcntr generated by MyEclipse - Hibernate Tools
 */

public class Xmlbkcntr  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String bcflag;
     private String ieflag;
     private Integer xmlbkkey;
     private Integer vslvoykey;
     private String cntrno;
     private String cntrtype;
     private String cntrcocode;
     private String cntrconame;
     private String flesign;
     private String sealnosh;
     private String sealnoca;
     private String sealnocu;
     private String sealnoac;
     private String sealnoto;
     private String sealnoaa;
     private String sealnoab;
     private String sealnoun1;
     private String sealnoun2;
     private String supplier;

    // Constructors

    /** default constructor */
    public Xmlbkcntr() {
    }

	/** minimal constructor */
    public Xmlbkcntr(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Xmlbkcntr(Integer mainkey, String bcflag, String ieflag, Integer xmlbkkey, Integer vslvoykey, String cntrno, String cntrtype, String cntrcocode, String cntrconame, String flesign, String sealnosh, String sealnoca, String sealnocu, String sealnoac, String sealnoto, String sealnoaa, String sealnoab, String sealnoun1, String sealnoun2) {
        this.mainkey = mainkey;
        this.bcflag = bcflag;
        this.ieflag = ieflag;
        this.xmlbkkey = xmlbkkey;
        this.vslvoykey = vslvoykey;
        this.cntrno = cntrno;
        this.cntrtype = cntrtype;
        this.cntrcocode = cntrcocode;
        this.cntrconame = cntrconame;
        this.flesign = flesign;
        this.sealnosh = sealnosh;
        this.sealnoca = sealnoca;
        this.sealnocu = sealnocu;
        this.sealnoac = sealnoac;
        this.sealnoto = sealnoto;
        this.sealnoaa = sealnoaa;
        this.sealnoab = sealnoab;
        this.sealnoun1 = sealnoun1;
        this.sealnoun2 = sealnoun2;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getBcflag() {
        return this.bcflag;
    }
    
    public void setBcflag(String bcflag) {
        this.bcflag = bcflag;
    }

    public String getIeflag() {
        return this.ieflag;
    }
    
    public void setIeflag(String ieflag) {
        this.ieflag = ieflag;
    }

    public Integer getXmlbkkey() {
        return this.xmlbkkey;
    }
    
    public void setXmlbkkey(Integer xmlbkkey) {
        this.xmlbkkey = xmlbkkey;
    }

    public Integer getVslvoykey() {
        return this.vslvoykey;
    }
    
    public void setVslvoykey(Integer vslvoykey) {
        this.vslvoykey = vslvoykey;
    }

    public String getCntrno() {
        return this.cntrno;
    }
    
    public void setCntrno(String cntrno) {
        this.cntrno = cntrno;
    }

    public String getCntrtype() {
        return this.cntrtype;
    }
    
    public void setCntrtype(String cntrtype) {
        this.cntrtype = cntrtype;
    }

    public String getCntrcocode() {
        return this.cntrcocode;
    }
    
    public void setCntrcocode(String cntrcocode) {
        this.cntrcocode = cntrcocode;
    }

    public String getCntrconame() {
        return this.cntrconame;
    }
    
    public void setCntrconame(String cntrconame) {
        this.cntrconame = cntrconame;
    }

    public String getFlesign() {
        return this.flesign;
    }
    
    public void setFlesign(String flesign) {
        this.flesign = flesign;
    }

    public String getSealnosh() {
        return this.sealnosh;
    }
    
    public void setSealnosh(String sealnosh) {
        this.sealnosh = sealnosh;
    }

    public String getSealnoca() {
        return this.sealnoca;
    }
    
    public void setSealnoca(String sealnoca) {
        this.sealnoca = sealnoca;
    }

    public String getSealnocu() {
        return this.sealnocu;
    }
    
    public void setSealnocu(String sealnocu) {
        this.sealnocu = sealnocu;
    }

    public String getSealnoac() {
        return this.sealnoac;
    }
    
    public void setSealnoac(String sealnoac) {
        this.sealnoac = sealnoac;
    }

    public String getSealnoto() {
        return this.sealnoto;
    }
    
    public void setSealnoto(String sealnoto) {
        this.sealnoto = sealnoto;
    }

    public String getSealnoaa() {
        return this.sealnoaa;
    }
    
    public void setSealnoaa(String sealnoaa) {
        this.sealnoaa = sealnoaa;
    }

    public String getSealnoab() {
        return this.sealnoab;
    }
    
    public void setSealnoab(String sealnoab) {
        this.sealnoab = sealnoab;
    }

    public String getSealnoun1() {
        return this.sealnoun1;
    }
    
    public void setSealnoun1(String sealnoun1) {
        this.sealnoun1 = sealnoun1;
    }

    public String getSealnoun2() {
        return this.sealnoun2;
    }
    
    public void setSealnoun2(String sealnoun2) {
        this.sealnoun2 = sealnoun2;
    }

	public String getSupplier() {
		return supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}
   








}