package cosco.xml.mapping;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Xmlbooking generated by MyEclipse - Hibernate Tools
 */

public class Xmlbooking  implements java.io.Serializable {


    // Fields    
	 private Set<Xmlbkcargo> Xmlbkcargo = new HashSet<Xmlbkcargo>();
	 private Set<Xmlbkcntr> Xmlbkcntr = new HashSet<Xmlbkcntr>();
	 private Set<Xmlbkparty> Xmlbkparty = new HashSet<Xmlbkparty>();
	
     private Integer mainkey;
     private String bcflag;
     private String ieflag;
     private Integer vslvoykey;
     private String blno;
     private String carrcode;
     private String carrename;
     private String pccode;
     private String pcename;
     private String bktype;
     private String amdcode1;
     private String amdcode2;
     private String amdcode3;
     private String carrtype;
     private String deconsid;
     private String asblno;
     private Double gvmeasure;
     private Double cvamount;
     private String cvacurr;
     private String ldpcode;
     private Date ldpdate;
     private String dispcode;
     private Date dispdate;
     private String delpcode;
     private String delpname;
     private String transfrm;
     private String transend;
     private String rtcountry;
     private String consignp;
     private String custsts;
     private String splitflag;
     private String frtpayer;
     private Integer piece;
     private String pkgcode;
     private Double gtweight;
     private String pcdocid;
     private String pcdoctype;
     private String ddline;
     private String ddcity;
     private String ddentid;
     private String ddentname;
     private String ddpostid;
     private String ddcountry;
     private String handcode;
     private String mcarrid;
     private String mcarrcm1;
     private String mcarrty1;
     private String mcarrcm2;
     private String mcarrty2;
     private String mcarrcm3;
     private String mcarrty3;
     private String dgctname;
     private String dgctcm1;
     private String dgctty1;
     private String dgctcm2;
     private String dgctty2;
     private String dgctcm3;
     private String dgctty3;
     private String custpcode;
     private String remark;
     private String makercode;
     private String maker;
     private Date madetime;
     private String modicode;
     private String modifier;
     private Date moditime;
     private Integer apfirnums;
     private Integer apsecnums;
     private Integer apmodnums;
     private Integer apdelnums;
     private String xml2pre;


    // Constructors

    /** default constructor */
    public Xmlbooking() {
    }

	/** minimal constructor */
    public Xmlbooking(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Xmlbooking(Integer mainkey, String bcflag, String ieflag, Integer vslvoykey, String blno, String carrcode, String carrename, String pccode, String pcename, String bktype, String amdcode1, String amdcode2, String amdcode3, String carrtype, String deconsid, String asblno, Double gvmeasure, Double cvamount, String cvacurr, String ldpcode, Date ldpdate, String dispcode, Date dispdate, String delpcode, String delpname, String transfrm, String transend, String rtcountry, String consignp, String custsts, String splitflag, String frtpayer, Integer piece, String pkgcode, Double gtweight, String pcdocid, String pcdoctype, String ddline, String ddcity, String ddentid, String ddentname, String ddpostid, String ddcountry, String handcode, String mcarrid, String mcarrcm1, String mcarrty1, String mcarrcm2, String mcarrty2, String mcarrcm3, String mcarrty3, String dgctname, String dgctcm1, String dgctty1, String dgctcm2, String dgctty2, String dgctcm3, String dgctty3, String custpcode, String remark, String makercode, String maker, Date madetime, String modicode, String modifier, Date moditime, Integer apfirnums, Integer apsecnums, Integer apmodnums, Integer apdelnums, String xml2pre) {
        this.mainkey = mainkey;
        this.bcflag = bcflag;
        this.ieflag = ieflag;
        this.vslvoykey = vslvoykey;
        this.blno = blno;
        this.carrcode = carrcode;
        this.carrename = carrename;
        this.pccode = pccode;
        this.pcename = pcename;
        this.bktype = bktype;
        this.amdcode1 = amdcode1;
        this.amdcode2 = amdcode2;
        this.amdcode3 = amdcode3;
        this.carrtype = carrtype;
        this.deconsid = deconsid;
        this.asblno = asblno;
        this.gvmeasure = gvmeasure;
        this.cvamount = cvamount;
        this.cvacurr = cvacurr;
        this.ldpcode = ldpcode;
        this.ldpdate = ldpdate;
        this.dispcode = dispcode;
        this.dispdate = dispdate;
        this.delpcode = delpcode;
        this.delpname = delpname;
        this.transfrm = transfrm;
        this.transend = transend;
        this.rtcountry = rtcountry;
        this.consignp = consignp;
        this.custsts = custsts;
        this.splitflag = splitflag;
        this.frtpayer = frtpayer;
        this.piece = piece;
        this.pkgcode = pkgcode;
        this.gtweight = gtweight;
        this.pcdocid = pcdocid;
        this.pcdoctype = pcdoctype;
        this.ddline = ddline;
        this.ddcity = ddcity;
        this.ddentid = ddentid;
        this.ddentname = ddentname;
        this.ddpostid = ddpostid;
        this.ddcountry = ddcountry;
        this.handcode = handcode;
        this.mcarrid = mcarrid;
        this.mcarrcm1 = mcarrcm1;
        this.mcarrty1 = mcarrty1;
        this.mcarrcm2 = mcarrcm2;
        this.mcarrty2 = mcarrty2;
        this.mcarrcm3 = mcarrcm3;
        this.mcarrty3 = mcarrty3;
        this.dgctname = dgctname;
        this.dgctcm1 = dgctcm1;
        this.dgctty1 = dgctty1;
        this.dgctcm2 = dgctcm2;
        this.dgctty2 = dgctty2;
        this.dgctcm3 = dgctcm3;
        this.dgctty3 = dgctty3;
        this.custpcode = custpcode;
        this.remark = remark;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
        this.apfirnums = apfirnums;
        this.apsecnums = apsecnums;
        this.apmodnums = apmodnums;
        this.apdelnums = apdelnums;
        this.xml2pre = xml2pre;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getBcflag() {
        return this.bcflag;
    }
    
    public void setBcflag(String bcflag) {
        this.bcflag = bcflag;
    }

    public String getIeflag() {
        return this.ieflag;
    }
    
    public void setIeflag(String ieflag) {
        this.ieflag = ieflag;
    }

    public Integer getVslvoykey() {
        return this.vslvoykey;
    }
    
    public void setVslvoykey(Integer vslvoykey) {
        this.vslvoykey = vslvoykey;
    }

    public String getBlno() {
        return this.blno;
    }
    
    public void setBlno(String blno) {
        this.blno = blno;
    }

    public String getCarrcode() {
        return this.carrcode;
    }
    
    public void setCarrcode(String carrcode) {
        this.carrcode = carrcode;
    }

    public String getCarrename() {
        return this.carrename;
    }
    
    public void setCarrename(String carrename) {
        this.carrename = carrename;
    }

    public String getPccode() {
        return this.pccode;
    }
    
    public void setPccode(String pccode) {
        this.pccode = pccode;
    }

    public String getPcename() {
        return this.pcename;
    }
    
    public void setPcename(String pcename) {
        this.pcename = pcename;
    }

    public String getBktype() {
        return this.bktype;
    }
    
    public void setBktype(String bktype) {
        this.bktype = bktype;
    }

    public String getAmdcode1() {
        return this.amdcode1;
    }
    
    public void setAmdcode1(String amdcode1) {
        this.amdcode1 = amdcode1;
    }

    public String getAmdcode2() {
        return this.amdcode2;
    }
    
    public void setAmdcode2(String amdcode2) {
        this.amdcode2 = amdcode2;
    }

    public String getAmdcode3() {
        return this.amdcode3;
    }
    
    public void setAmdcode3(String amdcode3) {
        this.amdcode3 = amdcode3;
    }

    public String getCarrtype() {
        return this.carrtype;
    }
    
    public void setCarrtype(String carrtype) {
        this.carrtype = carrtype;
    }

    public String getDeconsid() {
        return this.deconsid;
    }
    
    public void setDeconsid(String deconsid) {
        this.deconsid = deconsid;
    }

    public String getAsblno() {
        return this.asblno;
    }
    
    public void setAsblno(String asblno) {
        this.asblno = asblno;
    }

    public Double getGvmeasure() {
        return this.gvmeasure;
    }
    
    public void setGvmeasure(Double gvmeasure) {
        this.gvmeasure = gvmeasure;
    }

    public Double getCvamount() {
        return this.cvamount;
    }
    
    public void setCvamount(Double cvamount) {
        this.cvamount = cvamount;
    }

    public String getCvacurr() {
        return this.cvacurr;
    }
    
    public void setCvacurr(String cvacurr) {
        this.cvacurr = cvacurr;
    }

    public String getLdpcode() {
        return this.ldpcode;
    }
    
    public void setLdpcode(String ldpcode) {
        this.ldpcode = ldpcode;
    }

    public Date getLdpdate() {
        return this.ldpdate;
    }
    
    public void setLdpdate(Date ldpdate) {
        this.ldpdate = ldpdate;
    }

    public String getDispcode() {
        return this.dispcode;
    }
    
    public void setDispcode(String dispcode) {
        this.dispcode = dispcode;
    }

    public Date getDispdate() {
        return this.dispdate;
    }
    
    public void setDispdate(Date dispdate) {
        this.dispdate = dispdate;
    }

    public String getDelpcode() {
        return this.delpcode;
    }
    
    public void setDelpcode(String delpcode) {
        this.delpcode = delpcode;
    }

    public String getDelpname() {
        return this.delpname;
    }
    
    public void setDelpname(String delpname) {
        this.delpname = delpname;
    }

    public String getTransfrm() {
        return this.transfrm;
    }
    
    public void setTransfrm(String transfrm) {
        this.transfrm = transfrm;
    }

    public String getTransend() {
        return this.transend;
    }
    
    public void setTransend(String transend) {
        this.transend = transend;
    }

    public String getRtcountry() {
        return this.rtcountry;
    }
    
    public void setRtcountry(String rtcountry) {
        this.rtcountry = rtcountry;
    }

    public String getConsignp() {
        return this.consignp;
    }
    
    public void setConsignp(String consignp) {
        this.consignp = consignp;
    }

    public String getCuststs() {
        return this.custsts;
    }
    
    public void setCuststs(String custsts) {
        this.custsts = custsts;
    }

    public String getSplitflag() {
        return this.splitflag;
    }
    
    public void setSplitflag(String splitflag) {
        this.splitflag = splitflag;
    }

    public String getFrtpayer() {
        return this.frtpayer;
    }
    
    public void setFrtpayer(String frtpayer) {
        this.frtpayer = frtpayer;
    }

    public Integer getPiece() {
        return this.piece;
    }
    
    public void setPiece(Integer piece) {
        this.piece = piece;
    }

    public String getPkgcode() {
        return this.pkgcode;
    }
    
    public void setPkgcode(String pkgcode) {
        this.pkgcode = pkgcode;
    }

    public Double getGtweight() {
        return this.gtweight;
    }
    
    public void setGtweight(Double gtweight) {
        this.gtweight = gtweight;
    }

    public String getPcdocid() {
        return this.pcdocid;
    }
    
    public void setPcdocid(String pcdocid) {
        this.pcdocid = pcdocid;
    }

    public String getPcdoctype() {
        return this.pcdoctype;
    }
    
    public void setPcdoctype(String pcdoctype) {
        this.pcdoctype = pcdoctype;
    }

    public String getDdline() {
        return this.ddline;
    }
    
    public void setDdline(String ddline) {
        this.ddline = ddline;
    }

    public String getDdcity() {
        return this.ddcity;
    }
    
    public void setDdcity(String ddcity) {
        this.ddcity = ddcity;
    }

    public String getDdentid() {
        return this.ddentid;
    }
    
    public void setDdentid(String ddentid) {
        this.ddentid = ddentid;
    }

    public String getDdentname() {
        return this.ddentname;
    }
    
    public void setDdentname(String ddentname) {
        this.ddentname = ddentname;
    }

    public String getDdpostid() {
        return this.ddpostid;
    }
    
    public void setDdpostid(String ddpostid) {
        this.ddpostid = ddpostid;
    }

    public String getDdcountry() {
        return this.ddcountry;
    }
    
    public void setDdcountry(String ddcountry) {
        this.ddcountry = ddcountry;
    }

    public String getHandcode() {
        return this.handcode;
    }
    
    public void setHandcode(String handcode) {
        this.handcode = handcode;
    }

    public String getMcarrid() {
        return this.mcarrid;
    }
    
    public void setMcarrid(String mcarrid) {
        this.mcarrid = mcarrid;
    }

    public String getMcarrcm1() {
        return this.mcarrcm1;
    }
    
    public void setMcarrcm1(String mcarrcm1) {
        this.mcarrcm1 = mcarrcm1;
    }

    public String getMcarrty1() {
        return this.mcarrty1;
    }
    
    public void setMcarrty1(String mcarrty1) {
        this.mcarrty1 = mcarrty1;
    }

    public String getMcarrcm2() {
        return this.mcarrcm2;
    }
    
    public void setMcarrcm2(String mcarrcm2) {
        this.mcarrcm2 = mcarrcm2;
    }

    public String getMcarrty2() {
        return this.mcarrty2;
    }
    
    public void setMcarrty2(String mcarrty2) {
        this.mcarrty2 = mcarrty2;
    }

    public String getMcarrcm3() {
        return this.mcarrcm3;
    }
    
    public void setMcarrcm3(String mcarrcm3) {
        this.mcarrcm3 = mcarrcm3;
    }

    public String getMcarrty3() {
        return this.mcarrty3;
    }
    
    public void setMcarrty3(String mcarrty3) {
        this.mcarrty3 = mcarrty3;
    }

    public String getDgctname() {
        return this.dgctname;
    }
    
    public void setDgctname(String dgctname) {
        this.dgctname = dgctname;
    }

    public String getDgctcm1() {
        return this.dgctcm1;
    }
    
    public void setDgctcm1(String dgctcm1) {
        this.dgctcm1 = dgctcm1;
    }

    public String getDgctty1() {
        return this.dgctty1;
    }
    
    public void setDgctty1(String dgctty1) {
        this.dgctty1 = dgctty1;
    }

    public String getDgctcm2() {
        return this.dgctcm2;
    }
    
    public void setDgctcm2(String dgctcm2) {
        this.dgctcm2 = dgctcm2;
    }

    public String getDgctty2() {
        return this.dgctty2;
    }
    
    public void setDgctty2(String dgctty2) {
        this.dgctty2 = dgctty2;
    }

    public String getDgctcm3() {
        return this.dgctcm3;
    }
    
    public void setDgctcm3(String dgctcm3) {
        this.dgctcm3 = dgctcm3;
    }

    public String getDgctty3() {
        return this.dgctty3;
    }
    
    public void setDgctty3(String dgctty3) {
        this.dgctty3 = dgctty3;
    }

    public String getCustpcode() {
        return this.custpcode;
    }
    
    public void setCustpcode(String custpcode) {
        this.custpcode = custpcode;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Date getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Date madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Date getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Date moditime) {
        this.moditime = moditime;
    }

    public Integer getApfirnums() {
        return this.apfirnums;
    }
    
    public void setApfirnums(Integer apfirnums) {
        this.apfirnums = apfirnums;
    }

    public Integer getApsecnums() {
        return this.apsecnums;
    }
    
    public void setApsecnums(Integer apsecnums) {
        this.apsecnums = apsecnums;
    }

    public Integer getApmodnums() {
        return this.apmodnums;
    }
    
    public void setApmodnums(Integer apmodnums) {
        this.apmodnums = apmodnums;
    }

    public Integer getApdelnums() {
        return this.apdelnums;
    }
    
    public void setApdelnums(Integer apdelnums) {
        this.apdelnums = apdelnums;
    }

    public String getXml2pre() {
        return this.xml2pre;
    }
    
    public void setXml2pre(String xml2pre) {
        this.xml2pre = xml2pre;
    }

	public Set<Xmlbkcargo> getXmlbkcargo() {
		return Xmlbkcargo;
	}

	public void setXmlbkcargo(Set<Xmlbkcargo> xmlbkcargo) {
		Xmlbkcargo = xmlbkcargo;
	}

	public Set<Xmlbkcntr> getXmlbkcntr() {
		return Xmlbkcntr;
	}

	public void setXmlbkcntr(Set<Xmlbkcntr> xmlbkcntr) {
		Xmlbkcntr = xmlbkcntr;
	}

	public Set<Xmlbkparty> getXmlbkparty() {
		return Xmlbkparty;
	}

	public void setXmlbkparty(Set<Xmlbkparty> xmlbkparty) {
		Xmlbkparty = xmlbkparty;
	}
   

}