package cosco.xml.mapping;



/**
 * Xmlmapping generated by MyEclipse - Hibernate Tools
 */

public class Xmlmapping  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String partycode;
     private String maptpcode;
     private String maptpname;
     private String lccode;
     private String lcname;
     private String excode;
     private String exname;
     private String notetext;
     private String vercode;
     private String ieflag;


    // Constructors

    /** default constructor */
    public Xmlmapping() {
    }

	/** minimal constructor */
    public Xmlmapping(Integer mainkey, String ieflag) {
        this.mainkey = mainkey;
        this.ieflag = ieflag;
    }
    
    /** full constructor */
    public Xmlmapping(Integer mainkey, String partycode, String maptpcode, String maptpname, String lccode, String lcname, String excode, String exname, String notetext, String vercode, String ieflag) {
        this.mainkey = mainkey;
        this.partycode = partycode;
        this.maptpcode = maptpcode;
        this.maptpname = maptpname;
        this.lccode = lccode;
        this.lcname = lcname;
        this.excode = excode;
        this.exname = exname;
        this.notetext = notetext;
        this.vercode = vercode;
        this.ieflag = ieflag;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getPartycode() {
        return this.partycode;
    }
    
    public void setPartycode(String partycode) {
        this.partycode = partycode;
    }

    public String getMaptpcode() {
        return this.maptpcode;
    }
    
    public void setMaptpcode(String maptpcode) {
        this.maptpcode = maptpcode;
    }

    public String getMaptpname() {
        return this.maptpname;
    }
    
    public void setMaptpname(String maptpname) {
        this.maptpname = maptpname;
    }

    public String getLccode() {
        return this.lccode;
    }
    
    public void setLccode(String lccode) {
        this.lccode = lccode;
    }

    public String getLcname() {
        return this.lcname;
    }
    
    public void setLcname(String lcname) {
        this.lcname = lcname;
    }

    public String getExcode() {
        return this.excode;
    }
    
    public void setExcode(String excode) {
        this.excode = excode;
    }

    public String getExname() {
        return this.exname;
    }
    
    public void setExname(String exname) {
        this.exname = exname;
    }

    public String getNotetext() {
        return this.notetext;
    }
    
    public void setNotetext(String notetext) {
        this.notetext = notetext;
    }

    public String getVercode() {
        return this.vercode;
    }
    
    public void setVercode(String vercode) {
        this.vercode = vercode;
    }

    public String getIeflag() {
        return this.ieflag;
    }
    
    public void setIeflag(String ieflag) {
        this.ieflag = ieflag;
    }
   








}