package cosco.vsagent.mapping.ecd;


import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import cosco.vsagent.mapping.Booking;


/**
 * Ecdbooking generated by MyEclipse - Hibernate Tools
 */

public class Ecdbooking  implements java.io.Serializable, Booking {


    // Fields    

     private Integer mainkey;
     private Integer vslvoykey;
     private String blno;
     private String mainblno;
     private String bkno;
     private String carrcode;
     private String carrename;
     private String bkoffcode;
     private String bkoffcname;
     private String bkcode;
     private String bkcname;
     private String rcvpcode;
     private String revpename;
     private String ldpcode;
     private String ldpename;
     private String transport;
     private String transename;
     private String dispcode;
     private String dispename;
     private String delpcode;
     private String delpename;
     private String carrtype;
     private String pccode;
     private String pcename;
     private String bktype;
     private String bachsign;
     private String secvslsign;
     private String mktcode;
     private String marketer;
     private String preload;
     private String factload;
     private String blppat;
     private String blcpat;
     private String blsignat;
     private String blsigndate;
     private String bkcount;
     private String mfcusign;
     private String mfblsign;
     private String makercode;
     private String maker;
     private Timestamp madetime;
     private String modicode;
     private String modifier;
     private Timestamp moditime;
     private String remark;
     private String blldp;
     private String bldelp;
     private String bldisp;
     private String sign;
     private String issendedi;
     private String ietype;
     private String iscuspre;
     private String prename;
     private String close_After;

     private String is_web = "1";
     private String vslkey_seq;
     private List<Ecdbkcargo> cargo = new ArrayList<Ecdbkcargo>();
     private List<Ecdbkcntr> cntr = new ArrayList<Ecdbkcntr>();
     private List<Ecdbkparty> party = new ArrayList<Ecdbkparty>();
     private Ecdbksec ecdbksec ;
     private String sequence;
    // Constructors

    

	/** default constructor */
    public Ecdbooking() {
    }

	/** minimal constructor */
    public Ecdbooking(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Ecdbooking(Integer mainkey, Integer vslvoykey, String blno, String mainblno, String bkno, String carrcode, String carrename, String bkoffcode, String bkoffcname, String bkcode, String bkcname, String rcvpcode, String revpename, String ldpcode, String ldpename, String transport, String transename, String dispcode, String dispename, String delpcode, String delpename, String carrtype, String pccode, String pcename, String bktype, String bachsign, String secvslsign, String mktcode, String marketer, String preload, String factload, String blppat, String blcpat, String blsignat, String blsigndate, String bkcount, String mfcusign, String mfblsign, String makercode, String maker, Timestamp madetime, String modicode, String modifier, Timestamp moditime, String remark, String blldp, String bldelp, String bldisp, String sign, String issendedi, String ietype, String iscuspre, String prename, String closeAfter) {
        this.mainkey = mainkey;
        this.vslvoykey = vslvoykey;
        this.blno = blno;
        this.mainblno = mainblno;
        this.bkno = bkno;
        this.carrcode = carrcode;
        this.carrename = carrename;
        this.bkoffcode = bkoffcode;
        this.bkoffcname = bkoffcname;
        this.bkcode = bkcode;
        this.bkcname = bkcname;
        this.rcvpcode = rcvpcode;
        this.revpename = revpename;
        this.ldpcode = ldpcode;
        this.ldpename = ldpename;
        this.transport = transport;
        this.transename = transename;
        this.dispcode = dispcode;
        this.dispename = dispename;
        this.delpcode = delpcode;
        this.delpename = delpename;
        this.carrtype = carrtype;
        this.pccode = pccode;
        this.pcename = pcename;
        this.bktype = bktype;
        this.bachsign = bachsign;
        this.secvslsign = secvslsign;
        this.mktcode = mktcode;
        this.marketer = marketer;
        this.preload = preload;
        this.factload = factload;
        this.blppat = blppat;
        this.blcpat = blcpat;
        this.blsignat = blsignat;
        this.blsigndate = blsigndate;
        this.bkcount = bkcount;
        this.mfcusign = mfcusign;
        this.mfblsign = mfblsign;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
        this.remark = remark;
        this.blldp = blldp;
        this.bldelp = bldelp;
        this.bldisp = bldisp;
        this.sign = sign;
        this.issendedi = issendedi;
        this.ietype = ietype;
        this.iscuspre = iscuspre;
        this.prename = prename;
        this.close_After = closeAfter;
    }

   
    // Property accessors

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMainkey()
	 */
    public Integer getMainkey() {
        return this.mainkey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMainkey(java.lang.Integer)
	 */
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getVslvoykey()
	 */
    public Integer getVslvoykey() {
        return this.vslvoykey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setVslvoykey(java.lang.Integer)
	 */
    public void setVslvoykey(Integer vslvoykey) {
        this.vslvoykey = vslvoykey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBlno()
	 */
    public String getBlno() {
        return this.blno;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBlno(java.lang.String)
	 */
    public void setBlno(String blno) {
        this.blno = blno;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMainblno()
	 */
    public String getMainblno() {
        return this.mainblno;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMainblno(java.lang.String)
	 */
    public void setMainblno(String mainblno) {
        this.mainblno = mainblno;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBkno()
	 */
    public String getBkno() {
        return this.bkno;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBkno(java.lang.String)
	 */
    public void setBkno(String bkno) {
        this.bkno = bkno;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getCarrcode()
	 */
    public String getCarrcode() {
        return this.carrcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setCarrcode(java.lang.String)
	 */
    public void setCarrcode(String carrcode) {
        this.carrcode = carrcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getCarrename()
	 */
    public String getCarrename() {
        return this.carrename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setCarrename(java.lang.String)
	 */
    public void setCarrename(String carrename) {
        this.carrename = carrename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBkoffcode()
	 */
    public String getBkoffcode() {
        return this.bkoffcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBkoffcode(java.lang.String)
	 */
    public void setBkoffcode(String bkoffcode) {
        this.bkoffcode = bkoffcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBkoffcname()
	 */
    public String getBkoffcname() {
        return this.bkoffcname;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBkoffcname(java.lang.String)
	 */
    public void setBkoffcname(String bkoffcname) {
        this.bkoffcname = bkoffcname;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBkcode()
	 */
    public String getBkcode() {
        return this.bkcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBkcode(java.lang.String)
	 */
    public void setBkcode(String bkcode) {
        this.bkcode = bkcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBkcname()
	 */
    public String getBkcname() {
        return this.bkcname;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBkcname(java.lang.String)
	 */
    public void setBkcname(String bkcname) {
        this.bkcname = bkcname;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getRcvpcode()
	 */
    public String getRcvpcode() {
        return this.rcvpcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setRcvpcode(java.lang.String)
	 */
    public void setRcvpcode(String rcvpcode) {
        this.rcvpcode = rcvpcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getRevpename()
	 */
    public String getRevpename() {
        return this.revpename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setRevpename(java.lang.String)
	 */
    public void setRevpename(String revpename) {
        this.revpename = revpename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getLdpcode()
	 */
    public String getLdpcode() {
        return this.ldpcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setLdpcode(java.lang.String)
	 */
    public void setLdpcode(String ldpcode) {
        this.ldpcode = ldpcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getLdpename()
	 */
    public String getLdpename() {
        return this.ldpename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setLdpename(java.lang.String)
	 */
    public void setLdpename(String ldpename) {
        this.ldpename = ldpename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getTransport()
	 */
    public String getTransport() {
        return this.transport;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setTransport(java.lang.String)
	 */
    public void setTransport(String transport) {
        this.transport = transport;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getTransename()
	 */
    public String getTransename() {
        return this.transename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setTransename(java.lang.String)
	 */
    public void setTransename(String transename) {
        this.transename = transename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getDispcode()
	 */
    public String getDispcode() {
        return this.dispcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setDispcode(java.lang.String)
	 */
    public void setDispcode(String dispcode) {
        this.dispcode = dispcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getDispename()
	 */
    public String getDispename() {
        return this.dispename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setDispename(java.lang.String)
	 */
    public void setDispename(String dispename) {
        this.dispename = dispename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getDelpcode()
	 */
    public String getDelpcode() {
        return this.delpcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setDelpcode(java.lang.String)
	 */
    public void setDelpcode(String delpcode) {
        this.delpcode = delpcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getDelpename()
	 */
    public String getDelpename() {
        return this.delpename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setDelpename(java.lang.String)
	 */
    public void setDelpename(String delpename) {
        this.delpename = delpename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getCarrtype()
	 */
    public String getCarrtype() {
        return this.carrtype;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setCarrtype(java.lang.String)
	 */
    public void setCarrtype(String carrtype) {
        this.carrtype = carrtype;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getPccode()
	 */
    public String getPccode() {
        return this.pccode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setPccode(java.lang.String)
	 */
    public void setPccode(String pccode) {
        this.pccode = pccode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getPcename()
	 */
    public String getPcename() {
        return this.pcename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setPcename(java.lang.String)
	 */
    public void setPcename(String pcename) {
        this.pcename = pcename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBktype()
	 */
    public String getBktype() {
        return this.bktype;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBktype(java.lang.String)
	 */
    public void setBktype(String bktype) {
        this.bktype = bktype;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBachsign()
	 */
    public String getBachsign() {
        return this.bachsign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBachsign(java.lang.String)
	 */
    public void setBachsign(String bachsign) {
        this.bachsign = bachsign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getSecvslsign()
	 */
    public String getSecvslsign() {
        return this.secvslsign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setSecvslsign(java.lang.String)
	 */
    public void setSecvslsign(String secvslsign) {
        this.secvslsign = secvslsign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMktcode()
	 */
    public String getMktcode() {
        return this.mktcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMktcode(java.lang.String)
	 */
    public void setMktcode(String mktcode) {
        this.mktcode = mktcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMarketer()
	 */
    public String getMarketer() {
        return this.marketer;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMarketer(java.lang.String)
	 */
    public void setMarketer(String marketer) {
        this.marketer = marketer;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getPreload()
	 */
    public String getPreload() {
        return this.preload;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setPreload(java.lang.String)
	 */
    public void setPreload(String preload) {
        this.preload = preload;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getFactload()
	 */
    public String getFactload() {
        return this.factload;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setFactload(java.lang.String)
	 */
    public void setFactload(String factload) {
        this.factload = factload;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBlppat()
	 */
    public String getBlppat() {
        return this.blppat;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBlppat(java.lang.String)
	 */
    public void setBlppat(String blppat) {
        this.blppat = blppat;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBlcpat()
	 */
    public String getBlcpat() {
        return this.blcpat;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBlcpat(java.lang.String)
	 */
    public void setBlcpat(String blcpat) {
        this.blcpat = blcpat;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBlsignat()
	 */
    public String getBlsignat() {
        return this.blsignat;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBlsignat(java.lang.String)
	 */
    public void setBlsignat(String blsignat) {
        this.blsignat = blsignat;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBlsigndate()
	 */
    public String getBlsigndate() {
        return this.blsigndate;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBlsigndate(java.lang.String)
	 */
    public void setBlsigndate(String blsigndate) {
        this.blsigndate = blsigndate;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBkcount()
	 */
    public String getBkcount() {
        return this.bkcount;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBkcount(java.lang.String)
	 */
    public void setBkcount(String bkcount) {
        this.bkcount = bkcount;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMfcusign()
	 */
    public String getMfcusign() {
        return this.mfcusign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMfcusign(java.lang.String)
	 */
    public void setMfcusign(String mfcusign) {
        this.mfcusign = mfcusign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMfblsign()
	 */
    public String getMfblsign() {
        return this.mfblsign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMfblsign(java.lang.String)
	 */
    public void setMfblsign(String mfblsign) {
        this.mfblsign = mfblsign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMakercode()
	 */
    public String getMakercode() {
        return this.makercode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMakercode(java.lang.String)
	 */
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMaker()
	 */
    public String getMaker() {
        return this.maker;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMaker(java.lang.String)
	 */
    public void setMaker(String maker) {
        this.maker = maker;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getMadetime()
	 */
    public Timestamp getMadetime() {
        return this.madetime;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setMadetime(java.util.Date)
	 */
    public void setMadetime(Timestamp madetime) {
        this.madetime = madetime;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getModicode()
	 */
    public String getModicode() {
        return this.modicode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setModicode(java.lang.String)
	 */
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getModifier()
	 */
    public String getModifier() {
        return this.modifier;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setModifier(java.lang.String)
	 */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getModitime()
	 */
    public Timestamp getModitime() {
        return this.moditime;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setModitime(java.util.Date)
	 */
    public void setModitime(Timestamp moditime) {
        this.moditime = moditime;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getRemark()
	 */
    public String getRemark() {
        return this.remark;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setRemark(java.lang.String)
	 */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBlldp()
	 */
    public String getBlldp() {
        return this.blldp;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBlldp(java.lang.String)
	 */
    public void setBlldp(String blldp) {
        this.blldp = blldp;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBldelp()
	 */
    public String getBldelp() {
        return this.bldelp;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBldelp(java.lang.String)
	 */
    public void setBldelp(String bldelp) {
        this.bldelp = bldelp;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getBldisp()
	 */
    public String getBldisp() {
        return this.bldisp;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setBldisp(java.lang.String)
	 */
    public void setBldisp(String bldisp) {
        this.bldisp = bldisp;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getSign()
	 */
    public String getSign() {
        return this.sign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setSign(java.lang.String)
	 */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getIssendedi()
	 */
    public String getIssendedi() {
        return this.issendedi;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setIssendedi(java.lang.String)
	 */
    public void setIssendedi(String issendedi) {
        this.issendedi = issendedi;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getIetype()
	 */
    public String getIetype() {
        return this.ietype;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setIetype(java.lang.String)
	 */
    public void setIetype(String ietype) {
        this.ietype = ietype;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getIscuspre()
	 */
    public String getIscuspre() {
        return this.iscuspre;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setIscuspre(java.lang.String)
	 */
    public void setIscuspre(String iscuspre) {
        this.iscuspre = iscuspre;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getPrename()
	 */
    public String getPrename() {
        return this.prename;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setPrename(java.lang.String)
	 */
    public void setPrename(String prename) {
        this.prename = prename;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#getCloseAfter()
	 */
    public String getCloseAfter() {
        return this.close_After;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBooking#setCloseAfter(java.lang.String)
	 */
    public void setCloseAfter(String closeAfter) {
        this.close_After = closeAfter;
    }

	public String getIsweb() {
		return is_web;
	}

	public void setIsweb(String isweb) {
		this.is_web = isweb;
	}

	public List<Ecdbkcargo> getCargo() {
		return cargo;
	}

	public void setCargo(List<Ecdbkcargo> cargo) {
		this.cargo = cargo;
	}

	public List<Ecdbkcntr> getCntr() {
		return cntr;
	}

	public void setCntr(List<Ecdbkcntr> cntr) {
		this.cntr = cntr;
	}

	public List<Ecdbkparty> getParty() {
		return party;
	}

	public void setParty(List<Ecdbkparty> party) {
		this.party = party;
	}

	public Ecdbksec getEcdbksec() {
		return ecdbksec;
	}

	public void setEcdbksec(Ecdbksec ecdbksec) {
		this.ecdbksec = ecdbksec;
	}

	public String getVslkey_seq() {
		return vslkey_seq;
	}

	public void setVslkey_seq(String vslkey_seq) {
		this.vslkey_seq = vslkey_seq;
	}

	public String getSequence() {
		return sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}
   








}