package cosco.vsagent.mapping.ecd;



import cosco.vsagent.mapping.Cntr;



/**
 * Ecdbkcntr generated by MyEclipse - Hibernate Tools
 */

public class Ecdbkcntr  implements java.io.Serializable, Cntr {


    // Fields    

     private Integer mainkey;
     private Integer bkkey;
     private Integer vslvoykey;
     private String cntrtype;
     private String cntrno;
     private String cntrcocode;
     private String cntrconame;
     private String dockcode;
     private String dockname;
     private String sealno;
     private Integer piece;
     private String pkgcode;
     private String pkgname;
     private Double ntweight;
     private Double tare;
     private Double measure;
     private String flesign;
     private String socsign;	
     private String validsign;	
     private String remark;
     private String location;
     private String overfront;
     private String overback;
     private String overleft;
     private String overright;
     private String overheight;
     private String vent;
     private String ventunit;
     private String vslkey_seq;
     private String blno_seq;
     private String bookblno;

    // Constructors

    public String getBookblno() {
		return bookblno;
	}

	public void setBookblno(String bookblno) {
		this.bookblno = bookblno;
	}

	/** default constructor */
    public Ecdbkcntr() {
    }

	/** minimal constructor */
    public Ecdbkcntr(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Ecdbkcntr(Integer mainkey, Integer bkkey, Integer vslvoykey, String cntrtype, String cntrno, String cntrcocode, String cntrconame, String dockcode, String dockname, String sealno, Integer piece, String pkgcode, String pkgname, Double ntweight, Double tare, Double measure, String flesign, String socsign, String validsign, String remark, String location, String overfront, String overback, String overleft, String overright, String overheight, String vent, String ventunit) {
        
    	this.mainkey = mainkey;
        this.bkkey = bkkey;
        this.vslvoykey = vslvoykey;
        this.cntrtype = cntrtype;
        this.cntrno = cntrno;
        this.cntrcocode = cntrcocode;
        this.cntrconame = cntrconame;
        this.dockcode = dockcode;
        this.dockname = dockname;
        this.sealno = sealno;
        this.piece = piece;
        this.pkgcode = pkgcode;
        this.pkgname = pkgname;
        this.ntweight = ntweight;
        this.tare = tare;
        this.measure = measure;
        this.flesign = flesign;
        this.socsign = socsign;
        this.validsign = validsign;
        this.remark = remark;
        this.location = location;
        this.overfront = overfront;
        this.overback = overback;
        this.overleft = overleft;
        this.overright = overright;
        this.overheight = overheight;
        this.vent = vent;
        this.ventunit = ventunit;
    }
    
    
    
    /** full constructor */
    public Ecdbkcntr(String bookblno, Integer mainkey, Integer bkkey, Integer vslvoykey, String cntrtype, String cntrno, String cntrcocode, String cntrconame, String dockcode, String dockname, String sealno, Integer piece, String pkgcode, String pkgname, Double ntweight, Double tare, Double measure, String flesign, String socsign, String validsign, String remark, String location, String overfront, String overback, String overleft, String overright, String overheight, String vent, String ventunit) {
    	this.bookblno = bookblno;
    	this.mainkey = mainkey;
        this.bkkey = bkkey;
        this.vslvoykey = vslvoykey;
        this.cntrtype = cntrtype;
        this.cntrno = cntrno;
        this.cntrcocode = cntrcocode;
        this.cntrconame = cntrconame;
        this.dockcode = dockcode;
        this.dockname = dockname;
        this.sealno = sealno;
        this.piece = piece;
        this.pkgcode = pkgcode;
        this.pkgname = pkgname;
        this.ntweight = ntweight;
        this.tare = tare;
        this.measure = measure;
        this.flesign = flesign;
        this.socsign = socsign;
        this.validsign = validsign;
        this.remark = remark;
        this.location = location;
        this.overfront = overfront;
        this.overback = overback;
        this.overleft = overleft;
        this.overright = overright;
        this.overheight = overheight;
        this.vent = vent;
        this.ventunit = ventunit;
    }

   
    // Property accessors

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getMainkey()
	 */
    public Integer getMainkey() {
        return this.mainkey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setMainkey(java.lang.Integer)
	 */
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getBkkey()
	 */
    public Integer getBkkey() {
        return this.bkkey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setBkkey(java.lang.Integer)
	 */
    public void setBkkey(Integer bkkey) {
        this.bkkey = bkkey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getVslvoykey()
	 */
    public Integer getVslvoykey() {
        return this.vslvoykey;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setVslvoykey(java.lang.Integer)
	 */
    public void setVslvoykey(Integer vslvoykey) {
        this.vslvoykey = vslvoykey;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getCntrtype()
	 */
    public String getCntrtype() {
        return this.cntrtype;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setCntrtype(java.lang.String)
	 */
    public void setCntrtype(String cntrtype) {
        this.cntrtype = cntrtype;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getCntrno()
	 */
    public String getCntrno() {
        return this.cntrno;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setCntrno(java.lang.String)
	 */
    public void setCntrno(String cntrno) {
        this.cntrno = cntrno;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getCntrcocode()
	 */
    public String getCntrcocode() {
        return this.cntrcocode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setCntrcocode(java.lang.String)
	 */
    public void setCntrcocode(String cntrcocode) {
        this.cntrcocode = cntrcocode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getCntrconame()
	 */
    public String getCntrconame() {
        return this.cntrconame;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setCntrconame(java.lang.String)
	 */
    public void setCntrconame(String cntrconame) {
        this.cntrconame = cntrconame;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getDockcode()
	 */
    public String getDockcode() {
        return this.dockcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setDockcode(java.lang.String)
	 */
    public void setDockcode(String dockcode) {
        this.dockcode = dockcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getDockname()
	 */
    public String getDockname() {
        return this.dockname;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setDockname(java.lang.String)
	 */
    public void setDockname(String dockname) {
        this.dockname = dockname;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getSealno()
	 */
    public String getSealno() {
        return this.sealno;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setSealno(java.lang.String)
	 */
    public void setSealno(String sealno) {
        this.sealno = sealno;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getPiece()
	 */
    public Integer getPiece() {
        return this.piece;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setPiece(java.lang.Integer)
	 */
    public void setPiece(Integer piece) {
        this.piece = piece;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getPkgcode()
	 */
    public String getPkgcode() {
        return this.pkgcode;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setPkgcode(java.lang.String)
	 */
    public void setPkgcode(String pkgcode) {
        this.pkgcode = pkgcode;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getPkgname()
	 */
    public String getPkgname() {
        return this.pkgname;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setPkgname(java.lang.String)
	 */
    public void setPkgname(String pkgname) {
        this.pkgname = pkgname;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getNtweight()
	 */
    public Double getNtweight() {
        return this.ntweight;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setNtweight(java.lang.Double)
	 */
    public void setNtweight(Double ntweight) {
        this.ntweight = ntweight;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getTare()
	 */
    public Double getTare() {
        return this.tare;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setTare(java.lang.Double)
	 */
    public void setTare(Double tare) {
        this.tare = tare;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getMeasure()
	 */
    public Double getMeasure() {
        return this.measure;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setMeasure(java.lang.Double)
	 */
    public void setMeasure(Double measure) {
        this.measure = measure;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getFlesign()
	 */
    public String getFlesign() {
        return this.flesign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setFlesign(java.lang.String)
	 */
    public void setFlesign(String flesign) {
        this.flesign = flesign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getSocsign()
	 */
    public String getSocsign() {
        return this.socsign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setSocsign(java.lang.String)
	 */
    public void setSocsign(String socsign) {
        this.socsign = socsign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getValidsign()
	 */
    public String getValidsign() {
        return this.validsign;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setValidsign(java.lang.String)
	 */
    public void setValidsign(String validsign) {
        this.validsign = validsign;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getRemark()
	 */
    public String getRemark() {
        return this.remark;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setRemark(java.lang.String)
	 */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getLocation()
	 */
    public String getLocation() {
        return this.location;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setLocation(java.lang.String)
	 */
    public void setLocation(String location) {
        this.location = location;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getOverfront()
	 */
    public String getOverfront() {
        return this.overfront;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setOverfront(java.lang.String)
	 */
    public void setOverfront(String overfront) {
        this.overfront = overfront;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getOverback()
	 */
    public String getOverback() {
        return this.overback;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setOverback(java.lang.String)
	 */
    public void setOverback(String overback) {
        this.overback = overback;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getOverleft()
	 */
    public String getOverleft() {
        return this.overleft;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setOverleft(java.lang.String)
	 */
    public void setOverleft(String overleft) {
        this.overleft = overleft;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getOverright()
	 */
    public String getOverright() {
        return this.overright;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setOverright(java.lang.String)
	 */
    public void setOverright(String overright) {
        this.overright = overright;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getOverheight()
	 */
    public String getOverheight() {
        return this.overheight;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setOverheight(java.lang.String)
	 */
    public void setOverheight(String overheight) {
        this.overheight = overheight;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getVent()
	 */
    public String getVent() {
        return this.vent;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setVent(java.lang.String)
	 */
    public void setVent(String vent) {
        this.vent = vent;
    }

    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#getVentunit()
	 */
    public String getVentunit() {
        return this.ventunit;
    }
    
    /* (non-Javadoc)
	 * @see cn.netstars.vsagent.mapping.ecd.IBkcntr#setVentunit(java.lang.String)
	 */
    public void setVentunit(String ventunit) {
        this.ventunit = ventunit;
    }

	public String getVslkey_seq() {
		return vslkey_seq;
	}

	public void setVslkey_seq(String vslkey_seq) {
		this.vslkey_seq = vslkey_seq;
	}

	public String getBlno_seq() {
		return blno_seq;
	}

	public void setBlno_seq(String blno_seq) {
		this.blno_seq = blno_seq;
	}
   








}