package cosco.vsagent.mapping.base;

import java.sql.Timestamp;
import java.util.Date;


/**
 * Bascountry generated by MyEclipse - Hibernate Tools
 */

public class Bascountry  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String nationcode;
     private String cname;
     private String ename;
     private String makercode;
     private String maker;
     private Timestamp madetime;
     private String modicode;
     private String modifier;
     private Timestamp moditime;


    // Constructors

    /** default constructor */
    public Bascountry() {
    }

	/** minimal constructor */
    public Bascountry(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Bascountry(Integer mainkey, String nationcode, String cname, String ename, String makercode, String maker, Timestamp madetime, String modicode, String modifier, Timestamp moditime) {
        this.mainkey = mainkey;
        this.nationcode = nationcode;
        this.cname = cname;
        this.ename = ename;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getNationcode() {
        return this.nationcode;
    }
    
    public void setNationcode(String nationcode) {
        this.nationcode = nationcode;
    }

    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Timestamp getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Timestamp madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Timestamp moditime) {
        this.moditime = moditime;
    }
   








}