package cosco.vsagent.mapping.base;

import java.sql.Timestamp;



/**
 * Basline generated by MyEclipse - Hibernate Tools
 */

public class Basline  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String linecode;
     private String linename;
     private String makercode;
     private String maker;
     private Timestamp madetime;
     private String modicode;
     private String modifier;
     private Timestamp moditime;
     private String portlist;
     private String operator;
     private String schedule;
     private String linetype;


    // Constructors

    /** default constructor */
    public Basline() {
    }

	/** minimal constructor */
    public Basline(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Basline(Integer mainkey, String linecode, String linename, String makercode, String maker, Timestamp madetime, String modicode, String modifier, Timestamp moditime, String portlist, String operator, String schedule, String linetype) {
        this.mainkey = mainkey;
        this.linecode = linecode;
        this.linename = linename;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
        this.portlist = portlist;
        this.operator = operator;
        this.schedule = schedule;
        this.linetype = linetype;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getLinecode() {
        return this.linecode;
    }
    
    public void setLinecode(String linecode) {
        this.linecode = linecode;
    }

    public String getLinename() {
        return this.linename;
    }
    
    public void setLinename(String linename) {
        this.linename = linename;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Timestamp getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Timestamp madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Timestamp moditime) {
        this.moditime = moditime;
    }

    public String getPortlist() {
        return this.portlist;
    }
    
    public void setPortlist(String portlist) {
        this.portlist = portlist;
    }

    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }

    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }

    public String getLinetype() {
        return this.linetype;
    }
    
    public void setLinetype(String linetype) {
        this.linetype = linetype;
    }
   








}