package cosco.vsagent.mapping.base;

import java.sql.Timestamp;


/**
 * Baspaytype generated by MyEclipse - Hibernate Tools
 */

public class Baspaytype  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String paycode;
     private String payname;
     private String makercode;
     private String maker;
     private Timestamp madetime;
     private String modicode;
     private String modifier;
     private Timestamp moditime;


    // Constructors

    /** default constructor */
    public Baspaytype() {
    }

	/** minimal constructor */
    public Baspaytype(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Baspaytype(Integer mainkey, String paycode, String payname, String makercode, String maker, Timestamp madetime, String modicode, String modifier, Timestamp moditime) {
        this.mainkey = mainkey;
        this.paycode = paycode;
        this.payname = payname;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getPaycode() {
        return this.paycode;
    }
    
    public void setPaycode(String paycode) {
        this.paycode = paycode;
    }

    public String getPayname() {
        return this.payname;
    }
    
    public void setPayname(String payname) {
        this.payname = payname;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Timestamp getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Timestamp madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Timestamp moditime) {
        this.moditime = moditime;
    }
   








}