package cosco.vsagent.mapping.base;

import java.sql.Date;
import java.sql.Timestamp;


/**
 * Baspackage generated by MyEclipse - Hibernate Tools
 */

public class Baspackage  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;
     private String pkgcode;
     private String pkgname;
     private String makercode;
     private String maker;
     private Timestamp madetime;
     private String modicode;
     private String modifier;
     private Timestamp moditime;
     private String Sequence;

    // Constructors

    /** default constructor */
    public Baspackage() {
    }

	public String getSequence() {
		return this.Sequence;
	}

	public  void setSequence(String sequence) {
		this.Sequence = sequence;
	}

	/** minimal constructor */
    public Baspackage(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Baspackage(Integer mainkey, String pkgcode, String pkgname, String makercode, String maker, Timestamp madetime, String modicode, String modifier, Timestamp moditime) {
        this.mainkey = mainkey;
        this.pkgcode = pkgcode;
        this.pkgname = pkgname;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getPkgcode() {
        return this.pkgcode;
    }
    
    public void setPkgcode(String pkgcode) {
        this.pkgcode = pkgcode;
    }

    public String getPkgname() {
        return this.pkgname;
    }
    
    public void setPkgname(String pkgname) {
        this.pkgname = pkgname;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Timestamp getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Timestamp madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Timestamp moditime) {
        this.moditime = moditime;
    }
   








}