package cosco.vsagent.mapping.base;

import java.sql.Timestamp;
import java.util.Date;


/**
 * Basvslmsg generated by MyEclipse - Hibernate Tools
 */

public class Basvslmsg  implements java.io.Serializable {


    // Fields    

     private Integer mainkey;//主键
     private String shipcode;//船舶呼号
     private String vslcode;//船舶代码
     private String enname;//英文名称
     private String cnname;//中文名称
     private String nationcode;//国籍代码
     private String nationenam;//国籍英文
     private String nationcnam;//国籍中文
     private String nationpcod;
     private String nationpnam;
     private String ownercode;
     private String ownername;
     private String ownertype;
     private String typecode;
     private String typename;
     private String length;
     private String width;
     private String height;
     private Double netton;
     private Double grosston;
     private Double loadton;
     private String fulldraft;
     private String lightdraft;
     private Long holdteu;
     private Long deckteu;
     private String packnum;
     private String bulknum;
     private String horsepower;
     private String speed;
     private String hatchnum;
     private String gearset;
     private String email;
     private String faxno;
     private String isscno;
     private String isscclass;
     private String remark;
     private String sanitation;
     private String plagueno;
     private String deptcode;
     private String deptname;
     private String tel;
     private String mobile;
     private String tlx;
     private Long sumteu;
     private String selfagent;
     private String online;
     private String makercode;
     private String maker;
     private Timestamp madetime;
     private String modicode;
     private String modifier;
     private Timestamp moditime;
     private String linecode;
     private String linename;
     private String builddate;
     private Timestamp secure_Certificate_Chday;
     private String Sequence;
     
    // Constructors

    public String getSequence() {
		return Sequence;
	}

	public void setSequence(String sequence) {
		Sequence = sequence;
	}

	public Timestamp getSecure_Certificate_Chday() {
		return secure_Certificate_Chday;
	}

	public void setSecure_Certificate_Chday(Timestamp secure_Certificate_Chday) {
		this.secure_Certificate_Chday = secure_Certificate_Chday;
	}

	/** default constructor */
    public Basvslmsg() {
    }

	/** minimal constructor */
    public Basvslmsg(Integer mainkey) {
        this.mainkey = mainkey;
    }
    
    /** full constructor */
    public Basvslmsg(Integer mainkey, String shipcode, String vslcode, String enname, String cnname, String nationcode, String nationenam, String nationcnam, String nationpcod, String nationpnam, String ownercode, String ownername, String ownertype, String typecode, String typename, String length, String width, String height, Double netton, Double grosston, Double loadton, String fulldraft, String lightdraft, Long holdteu, Long deckteu, String packnum, String bulknum, String horsepower, String speed, String hatchnum, String gearset, String email, String faxno, String isscno, String isscclass, String remark, String sanitation, String plagueno, String deptcode, String deptname, String tel, String mobile, String tlx, Long sumteu, String selfagent, String online, String makercode, String maker, Timestamp madetime, String modicode, String modifier, Timestamp moditime, String linecode, String linename, String builddate, Timestamp secureCertificateChday) {
        this.mainkey = mainkey;
        this.shipcode = shipcode;
        this.vslcode = vslcode;
        this.enname = enname;
        this.cnname = cnname;
        this.nationcode = nationcode;
        this.nationenam = nationenam;
        this.nationcnam = nationcnam;
        this.nationpcod = nationpcod;
        this.nationpnam = nationpnam;
        this.ownercode = ownercode;
        this.ownername = ownername;
        this.ownertype = ownertype;
        this.typecode = typecode;
        this.typename = typename;
        this.length = length;
        this.width = width;
        this.height = height;
        this.netton = netton;
        this.grosston = grosston;
        this.loadton = loadton;
        this.fulldraft = fulldraft;
        this.lightdraft = lightdraft;
        this.holdteu = holdteu;
        this.deckteu = deckteu;
        this.packnum = packnum;
        this.bulknum = bulknum;
        this.horsepower = horsepower;
        this.speed = speed;
        this.hatchnum = hatchnum;
        this.gearset = gearset;
        this.email = email;
        this.faxno = faxno;
        this.isscno = isscno;
        this.isscclass = isscclass;
        this.remark = remark;
        this.sanitation = sanitation;
        this.plagueno = plagueno;
        this.deptcode = deptcode;
        this.deptname = deptname;
        this.tel = tel;
        this.mobile = mobile;
        this.tlx = tlx;
        this.sumteu = sumteu;
        this.selfagent = selfagent;
        this.online = online;
        this.makercode = makercode;
        this.maker = maker;
        this.madetime = madetime;
        this.modicode = modicode;
        this.modifier = modifier;
        this.moditime = moditime;
        this.linecode = linecode;
        this.linename = linename;
        this.builddate = builddate;
        this.secure_Certificate_Chday = secure_Certificate_Chday;
    }

   
    // Property accessors

    public Integer getMainkey() {
        return this.mainkey;
    }
    
    public void setMainkey(Integer mainkey) {
        this.mainkey = mainkey;
    }

    public String getShipcode() {
        return this.shipcode;
    }
    
    public void setShipcode(String shipcode) {
        this.shipcode = shipcode;
    }

    public String getVslcode() {
        return this.vslcode;
    }
    
    public void setVslcode(String vslcode) {
        this.vslcode = vslcode;
    }

    public String getEnname() {
        return this.enname;
    }
    
    public void setEnname(String enname) {
        this.enname = enname;
    }

    public String getCnname() {
        return this.cnname;
    }
    
    public void setCnname(String cnname) {
        this.cnname = cnname;
    }

    public String getNationcode() {
        return this.nationcode;
    }
    
    public void setNationcode(String nationcode) {
        this.nationcode = nationcode;
    }

    public String getNationenam() {
        return this.nationenam;
    }
    
    public void setNationenam(String nationenam) {
        this.nationenam = nationenam;
    }

    public String getNationcnam() {
        return this.nationcnam;
    }
    
    public void setNationcnam(String nationcnam) {
        this.nationcnam = nationcnam;
    }

    public String getNationpcod() {
        return this.nationpcod;
    }
    
    public void setNationpcod(String nationpcod) {
        this.nationpcod = nationpcod;
    }

    public String getNationpnam() {
        return this.nationpnam;
    }
    
    public void setNationpnam(String nationpnam) {
        this.nationpnam = nationpnam;
    }

    public String getOwnercode() {
        return this.ownercode;
    }
    
    public void setOwnercode(String ownercode) {
        this.ownercode = ownercode;
    }

    public String getOwnername() {
        return this.ownername;
    }
    
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }

    public String getOwnertype() {
        return this.ownertype;
    }
    
    public void setOwnertype(String ownertype) {
        this.ownertype = ownertype;
    }

    public String getTypecode() {
        return this.typecode;
    }
    
    public void setTypecode(String typecode) {
        this.typecode = typecode;
    }

    public String getTypename() {
        return this.typename;
    }
    
    public void setTypename(String typename) {
        this.typename = typename;
    }

    public String getLength() {
        return this.length;
    }
    
    public void setLength(String length) {
        this.length = length;
    }

    public String getWidth() {
        return this.width;
    }
    
    public void setWidth(String width) {
        this.width = width;
    }

    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }

    public Double getNetton() {
        return this.netton;
    }
    
    public void setNetton(Double netton) {
        this.netton = netton;
    }

    public Double getGrosston() {
        return this.grosston;
    }
    
    public void setGrosston(Double grosston) {
        this.grosston = grosston;
    }

    public Double getLoadton() {
        return this.loadton;
    }
    
    public void setLoadton(Double loadton) {
        this.loadton = loadton;
    }

    public String getFulldraft() {
        return this.fulldraft;
    }
    
    public void setFulldraft(String fulldraft) {
        this.fulldraft = fulldraft;
    }

    public String getLightdraft() {
        return this.lightdraft;
    }
    
    public void setLightdraft(String lightdraft) {
        this.lightdraft = lightdraft;
    }

    public Long getHoldteu() {
        return this.holdteu;
    }
    
    public void setHoldteu(Long holdteu) {
        this.holdteu = holdteu;
    }

    public Long getDeckteu() {
        return this.deckteu;
    }
    
    public void setDeckteu(Long deckteu) {
        this.deckteu = deckteu;
    }

    public String getPacknum() {
        return this.packnum;
    }
    
    public void setPacknum(String packnum) {
        this.packnum = packnum;
    }

    public String getBulknum() {
        return this.bulknum;
    }
    
    public void setBulknum(String bulknum) {
        this.bulknum = bulknum;
    }

    public String getHorsepower() {
        return this.horsepower;
    }
    
    public void setHorsepower(String horsepower) {
        this.horsepower = horsepower;
    }

    public String getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(String speed) {
        this.speed = speed;
    }

    public String getHatchnum() {
        return this.hatchnum;
    }
    
    public void setHatchnum(String hatchnum) {
        this.hatchnum = hatchnum;
    }

    public String getGearset() {
        return this.gearset;
    }
    
    public void setGearset(String gearset) {
        this.gearset = gearset;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getFaxno() {
        return this.faxno;
    }
    
    public void setFaxno(String faxno) {
        this.faxno = faxno;
    }

    public String getIsscno() {
        return this.isscno;
    }
    
    public void setIsscno(String isscno) {
        this.isscno = isscno;
    }

    public String getIsscclass() {
        return this.isscclass;
    }
    
    public void setIsscclass(String isscclass) {
        this.isscclass = isscclass;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSanitation() {
        return this.sanitation;
    }
    
    public void setSanitation(String sanitation) {
        this.sanitation = sanitation;
    }

    public String getPlagueno() {
        return this.plagueno;
    }
    
    public void setPlagueno(String plagueno) {
        this.plagueno = plagueno;
    }

    public String getDeptcode() {
        return this.deptcode;
    }
    
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode;
    }

    public String getDeptname() {
        return this.deptname;
    }
    
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTlx() {
        return this.tlx;
    }
    
    public void setTlx(String tlx) {
        this.tlx = tlx;
    }

    public Long getSumteu() {
        return this.sumteu;
    }
    
    public void setSumteu(Long sumteu) {
        this.sumteu = sumteu;
    }

    public String getSelfagent() {
        return this.selfagent;
    }
    
    public void setSelfagent(String selfagent) {
        this.selfagent = selfagent;
    }

    public String getOnline() {
        return this.online;
    }
    
    public void setOnline(String online) {
        this.online = online;
    }

    public String getMakercode() {
        return this.makercode;
    }
    
    public void setMakercode(String makercode) {
        this.makercode = makercode;
    }

    public String getMaker() {
        return this.maker;
    }
    
    public void setMaker(String maker) {
        this.maker = maker;
    }

    public Timestamp getMadetime() {
        return this.madetime;
    }
    
    public void setMadetime(Timestamp madetime) {
        this.madetime = madetime;
    }

    public String getModicode() {
        return this.modicode;
    }
    
    public void setModicode(String modicode) {
        this.modicode = modicode;
    }

    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getModitime() {
        return this.moditime;
    }
    
    public void setModitime(Timestamp moditime) {
        this.moditime = moditime;
    }

    public String getLinecode() {
        return this.linecode;
    }
    
    public void setLinecode(String linecode) {
        this.linecode = linecode;
    }

    public String getLinename() {
        return this.linename;
    }
    
    public void setLinename(String linename) {
        this.linename = linename;
    }

    public String getBuilddate() {
        return this.builddate;
    }
    
    public void setBuilddate(String builddate) {
        this.builddate = builddate;
    }

  








}